export enum QuestionActionTypes {
    GET_QUESTIONNARE = "get_questions",
    CHANGE_STEP = "change_step",
    SELECT_ANSWER = "select_answer",
    UPDATE_QUESTION = "update_question",
}

export interface QuestionState {
    answers: Answer;
    step: number;
}

export interface UserAnswer {
    id: number;
    user_id: number;
    meta_key: string;
    meta_value: string;
    created_at: string;
    updated_at: string;
}

export interface Answer {
    user_id: number;
    retireDefineWeeklyIncome: number | undefined;
    retireDefineNever: boolean | undefined;
    retireDefine20hours: boolean | undefined;
    retireDefineNoWork: boolean | undefined;
    extraSystematicYes: number | undefined;
    birthYear: string;
    wantToRetireAge: number;
    retireForRelaxing: number | undefined;
    retireForNoProblem: number | undefined;
    retireForEveryDayIsSaturDay: number | undefined;
    retireForVacation: number | undefined;
    retireExpenseNormal: number | undefined;
    retireExpenseMortage: number | undefined;
    retireExpenseEntertainment: number | undefined;
    retireExpenseTravel: number | undefined;
    retireIncomeTypePension: number | undefined;
    retireIncomeTypeSocial: number | undefined;
    retireIncomeTypePartTime: number | undefined;
    retireIncomeTypeRental: number | undefined;
    retireIncomeTypeOther: number | undefined;
    retireIncomePension: number | undefined;
    retireIncomeSocial: number | undefined;
    retireIncomePartTime: number | undefined;
    retireIncomeRental: number | undefined;
    retireIncomeOther: number | undefined;
    retireIncomePensionAmountPercent: number | undefined;
    retirementConcern1: number | undefined;
    retirementConcern2: number | undefined;
    retirementConcern3: number | undefined;
    retirementConcern4: number | undefined;
    retirementConcern5: number | undefined;
    systematicSavingAfterTax: number | undefined;
    systematicSavingTaxDeferred: number | undefined;
    systematicSavingTaxFree: number | undefined;
    oldEmployerPlans: number | undefined;
    marjorExpenseBeforeRetireWeeding: number | undefined;
    marjorExpenseBeforeRetirePropertyPurchase: number | undefined;
    retireInmarjorExpenseBeforeRetireEducation: number | undefined;
    marjorExpenseBeforeRetireHealthcare: number | undefined;
    marjorExpenseBeforeRetireOther: number | undefined;
    quickExperciseHouseholdIncome: number | undefined;
    quickExperciseSavedPercentage: number | undefined;
    quickExperciseMatchPercentage: number | undefined;
    totalSavedAfterTax: number | undefined;
    totalSavedTaxDeferred: number | undefined;
    totalSavedTaxFree: number | undefined;
    whyRetireTiredWorking: number | undefined;
    whyRetireFinancialFreedom: number | undefined;
    whatWouldUpsetLosingMoney: number | undefined;
    whatWouldUpsetPushingBackDate: number | undefined;
    decideSaveRetirementMathThing: number | undefined;
    decideSaveRetirementFeelingThing: number | undefined;
    valueMoreAccumulatingWelth: number | undefined;
    valueMoreProtectingWelth: number | undefined;
    HowKnowRetireInKnow: number | undefined;
    HowKnowRetireInNotSure: number | undefined;
    HowMuchToSuccessRetireNotSure: number | undefined;
    HowMuchToSuccessRetireProbably: number | undefined;
    HowMuchToSuccessRetireMoney: number | undefined;
    HowFeelMarketCrashedFind: number | undefined;
    HowFeelMarketCrashedNervous: number | undefined;
    HowDoMarketCrashedInvest: number | undefined;
    HowDoMarketCrashedCry: number | undefined;
    StillRetireMarketCrashedSure: number | undefined;
    StillRetireMarketCrashedNotSure: number | undefined;
    retirementReallyAcomplishNo: number | undefined;
    retirementReallyAcomplishYes: number | undefined;
    step2Answer_1: number;
    step2Answer_2: number;
    step2Answer_3: number;
    step2Answer_4: number;
    step5Answer_1: number;
    step5Answer_2: number;
    step6Answer_1: number;
    step6Answer_2: number;
    step6Answer_3: number;
    step6Answer_4: number;
    step6_follow1_answer_1: number;
    step6_follow1_answer_2: number;
    step6_follow1_answer_3: number;
    step6_follow1_answer_4: number;
    step6_follow2_answer_1: number;
    step6_follow2_answer_2: number;
    step6_follow2_answer_3: number;
    step6_follow3_answer_1: number;
    step6_follow3_answer_2: number;
    step6_follow3_answer_3: number;
    step6_follow4_answer_1: number;
    step6_follow4_answer_2: number;
    step6_follow4_answer_3: number;
    step8Answer_1: number;
    step8Answer_2: number;
    step8Answer_3: number;
    step8Answer_4: number;
    step8Answer_5: number;
    step9Answer_1: number;
    step9Answer_2: number;
    step9Answer_3: number;
    step9Answer_4: number;
    step9Answer_5: number;
    step10Answer_1: number;
    step10Answer_2: number;
    step10Answer_3: number;
    step10Answer_4: number;
    step11Answer_1: number;
    step11Answer_2: number;
    step11Answer_3: number;
    step11Answer_4: number;
    step11Answer_5: number;
    step12Answer_1: number;
    step12Answer_2: number;
    step12Answer_3: number;
    step12Answer_4: number;
    step13Answer_1: number;
    step13Answer_2: number;
    step14Answer_1: number;
    step14Answer_2: number;
    step15Answer_1: number;
    step15Answer_2: number;
    step16Answer_1: number;
    step16Answer_2: number;
    step16Answer_3: number;
    step16Answer_4: number;
    step17Answer_1: number;
    step17Answer_2: number;
    step18Answer_1: number;
    step18Answer_2: number;
    step19Answer_1: number;
    step19Answer_2: number;
    step20Answer_1: number;
    step20Answer_2: number;
    step21Answer_1: number;
    step21Answer_2: number;
    step21Answer_3: number;
    step21Answer_4: number;
    step22Answer_1: number;
    step22Answer_2: number;
    step23Answer_1: number;
    step23Answer_2: number;
    step23Answer_3: number;
    step23Answer_4: number;
    step24Answer_1: number;
    step24Answer_2: number;
    step24Answer_3: number;
    step24Answer_4: number;
    step26Answer_1: number;
    step26Answer_2: number;
    step27Answer_1: number;
    step27Answer_2: number;
    step28Answer_1: number;
    step28Answer_2: number;
    step29Answer_1: number;
    step29Answer_2: number;
    step30Answer_1: number;
    step30Answer_2: number;
    step31Answer_1: number;
    step31Answer_2: number;
    step32Answer_1: number;
    step32Answer_2: number;
    step33Answer_1: number;
    step33Answer_2: number;
    step34Answer_1: number;
    step34Answer_2: number;
    step35Answer_1: number;
    step35Answer_2: number;
    step36Answer_1: number;
    step36Answer_2: number;
    step37Answer_1: number;
    step37Answer_2: number;
    step40Answer_1: number;
    step40Answer_2: number;
    step40Answer_3: number;
}
